### ISSUE TITLE
fully decrypt on twrp9-encryptest wen

### ISSUE THREAD

**Issue by SmallPP420** [SmallPP420/new-test-9#1]

**Comment by lopestom** [comment]
Since **you started forking my repos like device_TWRP_UPA13 and others my repos** so you has been making more nonsense on top of nonsense. So I had made a decision to help him with my free time. But since your childhood decision I realized that you don't deserve much attention and I blocked you.
At the end you are putting credits {[(thanks)]}. **So you regret something?!**

I am now unlocking your profile. Despite knowing that you can create fake profiles or something like Fatso420 keep in mind your ignorant attitudes like not having deleted my profile and email from the forks you made!
This made everything I was trying to improve, the server found my profile doing too many tasks and stopped everything I could do in minutes.

After I figured out why that was, I got you baits and you took them all.

**I don't have the habit and attitude of blocking someone.** My choices to help someone are my freedom. But now I won't help you for your attitudes!

**Comment by SmallPP420** [comment]
sorry! i was trying to get twrp 11 on this device but decided to give up i should not have forked my bad ill delete them

**Comment by lopestom** [comment]
> sorry! i was trying to get twrp 11 on this device but decided to give up i should not have forked my bad ill delete them

TWRP 11 is new and need more improvements.

Wait patiently and after I can help you with my free time and obviously the device tree can fork.
But in this moment, patient!

**Comment by SmallPP420** [comment]
no need to help ive already given up

**Comment by SmallPP420** [comment]
also i'd like to clear up some stuff,

fatso420 used to be my main account until i lost its password and email but upon creating this account i found the password, again im sorry for the unnecessary forks but my fatso420 account was used for a building site named cirrus ci after i ran out of build credits for smallpp420 and the thank you message was in every boardconfig.mk! even the original twrp tree that i ported

**Comment by SmallPP420** [comment]
i also didnt realise forking would cause confusion i was trying to keep things organised for my self, again i am sorry

**Comment by lopestom** [comment]
> also i'd like to clear up some stuff,
> 
> fatso420 used to be my main account until i lost its password and email but upon creating this account i found the password, again im sorry for the unnecessary forks but my fatso420 account was used for a building site named cirrus ci after i ran out of build credits for smallpp420 and the thank you message was in every boardconfig.mk! even the original twrp tree that i ported

I see any BoardConfig file. Because that I wrote about credit.

Now no need explain nothing.

Cheers
